[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "http://alfaisalgroup.com.sa/*"
  to = "https://alfaisalgroup.com.sa/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.alfaisalgroup.com.sa/*"
  to = "https://alfaisalgroup.com.sa/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.alfaisalgroup.com.sa/*"
  to = "https://alfaisalgroup.com.sa/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/landing"
  to = "/landing/"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "upgrade-insecure-requests"
    Link = "</lovable-uploads/452d0f08-89bf-4863-9d95-46a23971500f.png>; rel=preload; as=image"